public enum CombatEventType
{
    MOVE_USED,
    COMBAT_ENDED,
    DAMAGE_DEALT,
    HEAL_RECEIVED,
    STATUS_EFFECT_APPLIED,
    TURN_CHANGED,
    XP_GAINED,
    MOVE_LEARNT,
    LEVEL_UP,
    RESOURCE_REGEN,
    RESOURCE_SPENT,
    ITEM_DROPPED,
    UNKNOWN
}
