package com.example.backend.models.combats;

public enum CombatEventType {
    MOVE_USED, COMBAT_ENDED, DAMAGE_DEALT, HEAL_RECEIVED, STATUS_EFFECT_APPLIED, STATUS_EFFECT_EXPIRED,
    TURN_CHANGED, XP_GAINED, MOVE_LEARNT, LEVEL_UP, RESOURCE_REGEN, ITEM_DROPPED, RESOURCE_SPENT,
    GOLD_GAINED, ENVIRONMENT_EFFECT,
}
